# Generated by Django 4.2.4 on 2023-09-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customers",
            old_name="scheduledAt",
            new_name="requestat",
        ),
        migrations.AddField(
            model_name="customers",
            name="scheduleddate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customers",
            name="address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="customers",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
