# Generated by Django 4.2.4 on 2023-09-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_project_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.RemoveField(
            model_name="picture",
            name="image",
        ),
        migrations.AddField(
            model_name="picture",
            name="images",
            field=models.ManyToManyField(related_name="pictures", to="app.image"),
        ),
    ]
