# Generated by Django 4.2.4 on 2023-09-19 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_image_remove_picture_image_picture_images"),
    ]

    operations = [
        migrations.RenameField(
            model_name="picture",
            old_name="images",
            new_name="image",
        ),
    ]
